CREATE TABLE `sensor_data` ( 
`id` INT NOT NULL AUTO_INCREMENT, 
`cas` DATETIME DEFAULT CURRENT_TIMESTAMP, 
`teplota` FLOAT DEFAULT NULL, 
`vlhkost` FLOAT DEFAULT NULL, 
`tlak` FLOAT DEFAULT NULL, 
`svietivost` FLOAT DEFAULT NULL, 
`zrazky` INT DEFAULT NULL, 
PRIMARY KEY (`id`) )
